language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'
  
install:
  - pip install --upgrade pip
  - pip --version
  - pip install --upgrade wheel
  - wheel version
  - pip install numpy==1.11.3 matplotlib==1.5.3 pandas==0.19.1 numba==0.29.0
  - pip install .

script: pytest
